### ISSUE TITLE
https://gitlab.sol1.net/SOL1/netbox-path-docker

### ISSUE THREAD

**Issue by dazza76** [sol1/netbox-path#2]
Hello Sol1, can we allow access to this in github ?

Cheers 

Darren

**Comment by davekempe** [comment]
Hi @dazza76 we would ultimately prefer to move the whole CI/CD to github and setup a docker repository from there. Sorry we left a reference the old gitlab repo in the README. 
This would get done faster if we had some commercial incentive, however not until mid January at this rate. 
I'm very interested to hear you might find Path useful, and would love some feedback on it. We are about to accelerate the development of it for a particular project, so expect some rapid fire changes. We may or may not improve the docker deployment at this time, depending on where the need is for our commercial project.

**Comment by sol1-matt** [comment]
That repo seems a little stale, I've removed references for now until we get time to look at this in more detail [09dd901](https://github.com/sol1/netbox-path/commit/09dd901d773a8fdd64113af66e41664babf865f8).
